# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6591aac37d1e714f2fdcc04ab0c14e1a"
name = "pincode-app"
handle = "pincode-app-6"
application_url = "https://plenty-blind-mad-guaranteed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pincode-checker-pro.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://plenty-blind-mad-guaranteed.trycloudflare.com/auth/callback",
  "https://plenty-blind-mad-guaranteed.trycloudflare.com/auth/shopify/callback",
  "https://plenty-blind-mad-guaranteed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
